name: xsdba
channels:
- conda-forge
dependencies:
- python >=3.10,<3.14
- boltons >=20.1
- bottleneck >=1.3.1
- cf_xarray >=0.10.0 # not sure if we need to be that strict
- cftime >=1.4.1
- dask >=2024.8.1
- importlib-metadata != 8.7.0 # conda-forge version is broken
- jsonpickle >=3.1.0
- numba >=0.58.1
- numpy >=1.26.0
- pint>=0.24.4
- scipy >=1.11.0
- statsmodels >=0.14.2
- typer >=0.16.0
- xarray >=2023.11.0
# Extras
- fastnanquantile >=0.0.2
- pot >=0.9.4
- xclim >=0.56.0
# SBCK
- eigen ==3.4.0
- pybind11 >=2.12.0
# Dev tools and testing
- bump-my-version >=1.2.3
- codespell >=2.4.1
- coverage >=7.5.0
- deptry >=0.23.0
- flake8 >=7.3.0
- flake8-rst-docstrings >=0.4.0
- flit >=3.11.0,<4.0
- h5netcdf >=1.3.0
- h5py >=3.12.1
- mypy >=1.18.2
- numpydoc >=1.9.0
- pip >=25.2
- pooch >=1.8.0
- pre-commit >=3.5.0
- pytest >=9.0.0
- pytest-cov >=5.0.0
- pytest-xdist >=3.2.0
- ruff >=0.13.3
- tox >=4.30.3
- vulture >=2.14
- watchdog >=4.0.0
- xdoctest>=1.1.5
- matplotlib >=3.6.0
- yamllint >=1.35.1
